project:
  type: website
  resources:
    - google04e9ede0b577c2d9.html
  
website:
  title: "Ogooue Stat"
  image: "logo/logo-files-7/logo.png"
  favicon: "logo/logo-files-7/favicon-32x32.png"
  open-graph: true
  site-url: https://labinc.ogoouestat.com
  site-path: "/"
  
  navbar:
    logo: "logo/logo-files-7/logo.png"
    toggle-position: right
    background: "#f0eeeb"
    logo-alt: "Ogooue Stat brand" 
    title: false
    collapse-below: lg
    page-navigation: true
    
    right:
      - text: "Case studies"
        href: case-studies/index.html
      - text: "Ideas"
        href: Ideas/index.html
      - text: "Parcours"
        href: Parcours/index.html
      - text: "Opinions"
        href: Opinions/index.html
      - text: "About LIOS"
        menu:
        - text: "Qui sommes nous?"
          href: about-lios.qmd
        - text: "Comment contribuer"
          href: contributor-docs/call-for-contributions.qmd
        - text: "Code de conduite"
          href: CODE_OF_CONDUCT.md
        - text: "Nous contacter"
          href: contact.qmd
        # - href: electricity.qmd
        #   text: Energie
        # - href: Routes.qmd
        #  text: Roads
        
  sidebar: 
    - title: "About us"
      contents:
        - about.qmd
        - viewpoints/editors-blog/posts/2022/10/18/meet-the-team.qmd
        - rwds-partners.qmd
        - contact.qmd
        - ts-and-cs.qmd
        - CODE_OF_CONDUCT.md
        - LICENCE.md
        
    - title: "Call for contributions"
    - title: "Careers"
    - title: "Ideas"
    - title: "Viewpoints"
  
  page-navigation: true

  back-to-top-navigation: false
  
  page-footer:
    background: "#000000"
    left: |
        [Copyright &copy; 2024 LabInc OgooueStat](/LICENCE.md)
    center:
      - href: https://twitter.com/lios
        icon: twitter-x
        aria-label: Twitter/X
      - href: https://fosstodon.org/@lios
        icon: mastodon
        aria-label: Mastodon
      - href: feeds.html
        icon: rss
        aria-label: LIOS rss

    right: |
      [Terms & Conditions](/ts-and-cs.qmd)
      
format:
  html:
    theme: [lux, rwds.scss]
    css: rwds.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 1000px
      margin-width: 250px

execute: 
  freeze: auto