project:
  type: website

website:
  title: "VhinsIncData"
  navbar:
    left:
      - href: Gabon.qmd
        text: Gabon
      - href: Economy.qmd
        text: Economy
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

