project:
  type: website
website:
  title: ""
  navbar:
    logo: "logo/logo-files-2/logo.png"
    home-button: Gabon.qmd
    left:
      - href: Gabon.qmd
        text: Home
      - href: Economy.qmd
        text: Economy
      - href: electricity.qmd
        text: Energie
      - href: Routes.qmd
        text: Roads
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
editor: visual
execute:
  freeze: false