project:
  type: website

website:
  title: "LabInc"
  navbar:
    left:
      - href: Gabon.qmd
        text: Home
      - href: Economy.qmd
        text: Economy
      - href: electricity.qmd
        text: Energie
      - href: Routes.qmd
        text: Roads

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual



