project:
  type: website

website:
  title: "VhinsIncData"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Gabon.qmd
        text: gabon
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

