---
title: "Conditions générales d'utilisation"
page-layout: article
sidebar: false
toc: true
title-block-banner: true
---

## Avertissement légal

Les déclarations de fait et d'opinion publiées sur ce site web sont celles des auteurs et contributeurs respectifs et ne reflètent pas nécessairement celles de LIOS (LabInc Ogooue Stat), de ses éditeurs, de la Royal Statistical Society (RSS), ou d'autres partenaires et bailleurs de fonds.

LIOS a préparé le contenu de ce site web de manière responsable et soignée. Cependant, LIOS, ses éditeurs, la RSS, ou d'autres partenaires et bailleurs de fonds déclinent toute garantie, explicite ou implicite, quant à l'exactitude des informations contenues dans l'un des matériaux de ce site web ou sur d'autres sites web liés ou sur tout lien subséquent. Cela inclut, mais sans limitation :

-   toute garantie implicite de qualité marchande et d'adaptation à un usage particulier.
-   toute responsabilité pour les dommages à votre matériel informatique, données, informations, matériaux et entreprise résultant des informations ou du manque d'informations disponibles.
-   toute erreur, omission ou inexactitude dans les informations.
-   toute décision prise ou action entreprise ou non en fonction des informations.

LIOS, ses éditeurs, la RSS, ou d'autres partenaires et bailleurs de fonds ne garantissent pas le contenu, l'exactitude, l'opportunité ou l'exhaustivité des informations ou que les informations peuvent être utilisées pour une raison quelconque et ne portent aucune responsabilité pour l'exactitude, le contenu ou la légalité de tout site lié ou de celui de tout lien subséquent. LIOS, ses éditeurs, la RSS, ou d'autres partenaires et bailleurs de fonds ne garantissent pas que le service du site web sera ininterrompu ou exempt d'erreurs ou que les défauts peuvent être corrigés.

LIOS, ses éditeurs, la RSS, ou d'autres partenaires et bailleurs de fonds ne seront pas responsables pour toute perte ou dommage (y compris sans limitation, dommage consécutif) découlant de l'utilisation, ou de la confiance en, les informations de ce site web, ou de l'utilisation de l'internet en général. Les liens vers d'autres sites web ou la publication d'annonces ne constituent pas une approbation ou une approbation par LIOS, ses éditeurs, la RSS, ou d'autres partenaires et bailleurs de fonds.

Ces avertissements et exclusions seront régis et interprétés conformément aux lois de l'Angleterre et du Pays de Galles sous la juridiction exclusive des tribunaux de l'Angleterre et du Pays de Galles. Ceux qui choisissent d'accéder à ce site depuis l'extérieur du Royaume-Uni sont responsables de la conformité avec les lois locales dans la mesure où ces lois locales sont applicables.

En utilisant ce site, vous acceptez ces termes et conditions d'utilisation.

## Quels sites web lions-nous ?

Les éditeurs et contributeurs de LIOS recommandent des liens web externes en fonction de leur pertinence et de leur utilité pour nos utilisateurs. La sélection et l'ajout de liens à notre site web sont entièrement à la discrétion de LIOS.

Il n'est pas de notre politique de conclure des accords pour des liens réciproques.

L'inclusion d'un lien vers le site web d'une organisation ou d'un individu ne constitue pas une approbation ou une approbation par LIOS, ses éditeurs, la RSS, ou d'autres partenaires et bailleurs de fonds de tout produit, service, politique ou opinion de l'organisation ou de l'individu. LIOS, ses éditeurs, la RSS, ou d'autres partenaires et bailleurs de fonds ne sont pas responsables du contenu des sites web externes.

## Quels sites web ne lions-nous pas ?

Nous ne lions pas les sites web qui contiennent du contenu raciste, sexuel ou trompeur; qui promeuvent la violence; qui sont en violation de toute loi du Royaume-Uni; ou qui sont autrement offensants pour des individus ou des groupes de personnes.

La décision de LIOS est définitive et aucune correspondance ne sera entamée.

<!-- Si vous souhaitez signaler une préoccupation, veuillez envoyer un email à [rwds@rss.org.uk](mailto:rwds@rss.org.uk). -->

## Politique de notification et de retrait

Si vous êtes titulaire de droits et que vous êtes préoccupé par le fait que vous avez trouvé du matériel sur notre site pour lequel vous n'avez pas donné votre permission, ou qui n'est pas couvert par une limitation ou une exception dans la loi nationale, veuillez nous contacter par écrit en indiquant les informations suivantes :

1.  Vos coordonnées.
2.  Les détails bibliographiques complets du matériel.
3.  L'URL exacte et complète où vous avez trouvé le matériel.
4.  Preuve que vous êtes le détenteur des droits et une déclaration que, sous peine de parjure, vous êtes le détenteur des droits ou êtes un représentant autorisé.

**Coordonnées :**
LabInc.

À réception de la notification, la procédure 'Notice and Takedown' est ensuite invoquée comme suit :

1.  Nous accuserons réception de votre plainte par email ou lettre et ferons une évaluation initiale de la validité et de la plausibilité de la plainte.
2.  À réception d'une plainte valide, le matériel sera temporairement retiré de notre site web en attendant une solution convenue.
3.  Nous contacterons le contributeur qui a déposé le matériel, si pertinent. Le contributeur sera informé que le matériel fait l'objet d'une plainte, sous quelles allégations, et sera encouragé à apaiser les plaintes concernées.
4.  Le plaignant et le contributeur seront encouragés à résoudre le problème rapidement et à l'amiable et à la satisfaction des deux parties, avec les résultats possibles suivants :
    -   Le matériel est replacé sur notre site web inchangé.
    -   Le matériel est replacé sur notre site web avec des modifications.
    -   Le matériel est retiré de façon permanente de notre site web.

Si le contributeur et le plaignant ne parviennent pas à s'entendre sur une solution, le matériel restera indisponible via le site web jusqu'à ce qu'une résolution soit trouvée.
